### PR TITLE
Updated the sample to work with SpringFox 2.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by dilipkrish**
It generates the documentation, though I haven't verified that it renders the correct documentation.

**NOTE:** The snapshot builds haven't been released yet, so this is just preliminary work to get the machinery for generating documentation.

### CODE REVIEW

**Comment by fehguy** [comment]
thanks @dilipkrish In the templates, it's called "springdox", and I swear I saw that in the repo.  Did you rename it to springfox after release?

**Comment by dilipkrish** [comment]
@fehguy yes we did. *DOX* has a bad connotation plus the spring folks requested us to change the name since its so similar to spring-restdocs.

**Comment by fehguy** [comment]
cool, I'll update the name in the templates.

**Comment by fehguy** [comment]
@dilipkrish I've regenerated the code with your changes.  I'm getting an error from the dependencies--can you please look at my pom.xml and let me know what needs to be changed?

```
fehguy-2:springfox-sample tony$ mvn clean package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-server 1.0.0
[INFO] ------------------------------------------------------------------------
Downloading: http://oss.jfrog.org/artifactory/oss-release-local/io/springfox/springfox-core/2.0.0-SNAPSHOT/springfox-core-2.0.0-SNAPSHOT.pom
Downloading: http://oss.jfrog.org/artifactory/oss-release-local/io/springfox/springfox-spi/2.0.0-SNAPSHOT/springfox-spi-2.0.0-SNAPSHOT.pom
Downloading: http://oss.jfrog.org/artifactory/oss-release-local/io/springfox/springfox-spring-web/2.0.0-SNAPSHOT/springfox-spring-web-2.0.0-SNAPSHOT.pom
Downloading: http://oss.jfrog.org/artifactory/oss-release-local/io/springfox/springfox-swagger2/2.0.0-SNAPSHOT/springfox-swagger2-2.0.0-SNAPSHOT.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.606s
[INFO] Finished at: Tue Mar 31 17:58:37 PDT 2015
[INFO] Final Memory: 7M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project swagger-server: Could not resolve dependencies for
project com.concur.service:swagger-server:jar:1.0.0: 
Failed to collect dependencies at io.springfox:springfox-core:jar:2.0.0-SNAPSHOT: 
Failed to read artifact descriptor for io.springfox:springfox-core:jar:2.0.0-SNAPSHOT: 
Could not transfer artifact io.springfox:springfox-core:pom:2.0.0-SNAPSHOT from/to jcenter-release (http://oss.jfrog.org/artifactory/oss-release-local/): 
Failed to transfer file: http://oss.jfrog.org/artifactory/oss-release-local/io/springfox/springfox-core/2.0.0-SNAPSHOT/springfox-core-2.0.0-SNAPSHOT.pom. 
Return code is: 409 , ReasonPhrase:Conflict. -> [Help 1]
```

**Comment by adrianbk** [comment]
You need to add the snapshot repo:
```xml
<repositories>
    <repository>
      <id>jcenter-snapshots</id>
      <name>jcenter</name>
      <url>http://oss.jfrog.org/artifactory/oss-snapshot-local/</url>
    </repository>
</repositories>
```

**Comment by adrianbk** [comment]
They are there: http://oss.jfrog.org/oss-snapshot-local/io/springfox/

**Comment by fehguy** [comment]
thanks, got it

**Comment by fehguy** [comment]
@dilipkrish when running your sample directly, I can't get a documentation listing.  What URL should I hit?

I'm running `mvn clean package jetty:run` and going to `http://localhost:8002/api-docs` with no luck

**Comment by dilipkrish** [comment]
@fehguy I made the context path the root ```/``` [here](https://github.com/dilipkrish/springfox-sample/blob/713a104cec29818806ed07dc7e5ab2084cf892b0/pom.xml#L34) and the default path relative to the context path for the application is ```/v2/api-docs``` so you should see that it renders at ```http://localhost:8002/v2/api-docs```. This is configurable and can be changed.

**Comment by dilipkrish** [comment]
This is mainly because swagger 1.2 and swagger 2.0 can co-exist. To preserve backwards compatibility we serve swagger 1.2 descriptions @ ```/api-docs```.

**Comment by fehguy** [comment]
got it.  I have your sample running now, I'll tweak the templates a bit and it'll be complete.

**Comment by fehguy** [comment]
OK it looks like everything is set!  Try it out @dilipkrish @adrianbk 
image

**Comment by dilipkrish** [comment]
:+1: One small change tho' the Readme.md that is generated still says ```[Springdox](https://github.com/springdox/springdox)```

**Comment by fehguy** [comment]
OK will fix that.  

How can I bundle the swagger-ui in this structure?  Since there's no web.xml, I can't build a webapp with src/main/resources.

**Comment by adrianbk** [comment]
@fehguy how do you want to bundle swagger-ui and what's not working with the build?

**Comment by fehguy** [comment]
Thinking something like this:

https://github.com/swagger-api/swagger-core/blob/develop_2.0/samples/java-jaxrs/pom.xml#L75-L117

grabs swagger-ui from github releases, unpacks it to the "right directory" ignoring index.html, which we provide in the build.

**Comment by dilipkrish** [comment]
@fehguy I pushed an update to the sample. It has a few kinks but here is [the commit](https://github.com/dilipkrish/springfox-sample/commit/c3b44579592b2dcda69abfe02f02f7094976065f) that makes it possible
/c @adrianbk

**Comment by dilipkrish** [comment]
Also the ultimate endpoint to hit is sdoc.jsp and not index.html.

@adrianbk looks like our library expects a webapp folder in a non-springboot scenario. Also do you think we ought to bundle a similar config in the swagger-ui library for non-spring boot usage?

**Comment by fehguy** [comment]
Thanks--is there no way to package up the static assets?  That would allow it to be the most current version.  If not, no worries.

**Comment by adrianbk** [comment]
@fehguy we are bundling a [webjar](http://www.webjars.org/) with the addition of a .jsp file [using Gradle](https://github.com/springfox/springfox/blob/master/springfox-swagger-ui/build.gradle). This should be very close to what you want. 

Our plan is to build some smarts into the springfox-swaggerui webjar to detect the top level swagger endpoints and present them in a dropdown. In the case of springfox we can have many within the same application - 2 swagger versions and what we have termed 'swagger groups'.  

I'm thinking it would be good if swagger-ui itself was bundled as a webjar with all static content - whether  or not it should include the index.html, I'm unsure (including an index.html can end up changing an applications welcome-file)
You could:

1. Wrap the swagger-ui build with Gradle an use it to build and publish the web jar - this kind of feels like the right place to do it! I'm happy to help out here if you want to go that route!

1. Wrestle with the Maven build in swagger-core and try to get it to download and build the webjar like we have done in [springfox-swagger-ui](https://github.com/springfox/springfox/tree/master/springfox-swagger-ui)

**Comment by fehguy** [comment]
OK cool.  My only thought was to avoid packaging the JSP dependencies, but let's follow the structure that you're following for springfox.  I'll merge your changes and have the generator include the webjar.

**Pull request merged**
